Migration to SLF4J
EXIficient/exificient-grammars pull request #22
Opened 2023-03-23 17:38 UTC by BBE78

Use of SLF4J logger instead of System.(out|err).println()

2023-03-24 08:37 UTC, danielpeintner requested changes
I ask you to remove all `if (LOGGER.isDebugEnabled())` wrappers since it is not necessary anymore with the logging framework in place...

2023-03-24 08:37 UTC, danielpeintner commented on src/main/java/com/siemens/ct/exi/grammars/EXIContentModelBuilder.java
> +			if (LOGGER.isDebugEnabled()) {
I don't think wrapping in `if` statement is necessary since LOGGER.debug will not log anything if DEBUG level is not reached.

2023-03-24 08:37 UTC, danielpeintner commented on src/main/java/com/siemens/ct/exi/grammars/EXIContentModelBuilder.java
> +			LOGGER.debug("\t{} --> {} --> {}", startState, xs, nextState);
same comment as above

2023-03-24 08:37 UTC, danielpeintner commented on src/main/java/com/siemens/ct/exi/grammars/regex/RangeToken.java
> +					if (LOGGER.isDebugEnabled())
again warpping in ` if (LOGGER.isDebugEnabled())` not needed

2023-03-24 08:37 UTC, danielpeintner commented on src/main/java/com/siemens/ct/exi/grammars/regex/RangeToken.java
> +					if (LOGGER.isDebugEnabled())
same as above

2023-03-24 08:37 UTC, danielpeintner commented on src/main/java/com/siemens/ct/exi/grammars/regex/RangeToken.java
> +					if (LOGGER.isDebugEnabled())
same

2023-03-30 18:39 UTC, BBE78 commented
> I ask you to remove all `if (LOGGER.isDebugEnabled())` wrappers since it is not necessary anymore with the logging framework in place...

Hi @danielpeintner, checking the log level before logging is a "best practice" to avoid memory allocation, string concatenation, for nothing... This rule is raised by several tools such as SonarQube https://rules.sonarsource.com/java/RSPEC-2629
I'm used to apply this recommendation in my source code, do you still want the check to be removed?

2023-03-31 08:29 UTC, danielpeintner commented
I don't have a very strong opinion but I guess we both can agree that the code looks nicer and less messy without this is additional `if (LOGGER.isDebugEnabled()) {` wrapper...

Moreover, with the formatting style of
`LOGGER.debug("Foo '{}' is happening", "x");`
the string is actually **not** concatenated.

If would be different if we do something like the following
`LOGGER.debug("Foo " + "xyz" + " is happening);`

see also some information here: https://logging.apache.org/log4j/log4j-2.3.2/performance.html

Anyhow, as I said, IF YOU STRONGLY PREFER to keep it as is I will not argue strongly... :)

2023-03-31 16:14 UTC, BBE78 commented
All debug level checks removed

2023-04-03 15:08 UTC, danielpeintner approved these changes

2023-04-03 15:08 UTC, merged